version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root 
      MARIADB_DATABASE: realmd
    volumes:
      - ./db/logon.sql:/docker-entrypoint-initdb.d/logon.sql:ro
    expose:
      - 3306
    ports:
      - 3306:3306